import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#fdb5aa",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#d6aa55",
        surface: "#fdf9f4",
        "on-secondary-fixed": "#360e0a",
        "tertiary-fixed-dim": "#eec068",
        "surface-tint": "#466558",
        "secondary-fixed": "#ffdad5",
        "on-error-container": "#93000a",
        "on-background": "#1c1c19",
        "on-surface": "#1c1c19",
        "inverse-primary": "#adcebe",
        "surface-variant": "#e6e2dd",
        "surface-dim": "#ddd9d5",
        outline: "#727974",
        "on-primary-container": "#98b9a9",
        "surface-container-low": "#f7f3ee",
        "on-tertiary-fixed-variant": "#5d4200",
        secondary: "#874f48",
        "on-secondary-fixed-variant": "#6b3832",
        "inverse-on-surface": "#f4f0eb",
        "surface-bright": "#fdf9f4",
        background: "#fdf9f4",
        "surface-container": "#f1ede8",
        "on-primary": "#ffffff",
        "on-secondary-container": "#79443d",
        "surface-container-highest": "#e6e2dd",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#012016",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "primary-fixed": "#c8eada",
        "on-primary-fixed-variant": "#2f4d41",
        tertiary: "#3e2a00",
        "primary-fixed-dim": "#adcebe",
        "primary-container": "#2c4a3e",
        primary: "#153328",
        "surface-container-high": "#ebe8e3",
        "outline-variant": "#c1c8c3",
        "secondary-container": "#fdb5aa",
        "tertiary-fixed": "#ffdea6",
        "inverse-surface": "#31302d",
        "on-surface-variant": "#414845",
        "tertiary-container": "#5a3f00",
        "on-tertiary-fixed": "#271900",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Noto Serif", "Georgia", "serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
        serif: ["Noto Serif", "Georgia", "serif"],
      },
      transitionDuration: {
        "400": "400ms",
      },
    },
  },
  plugins: [],
};

export default config;
